
project_id = "eovyjotxecnkqjylwdnj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[[api.endpoints]]
path = "/apply-transformation"
src = "./apply-transformation/index.ts"

[[api.endpoints]]
path = "/create-transformation"
src = "./create-transformation/index.ts"

[[api.endpoints]]
path = "/delete-transformation"
src = "./delete-transformation/index.ts"

[[api.endpoints]]
path = "/export-data"
src = "./export-data/index.ts"

[[api.endpoints]]
path = "/get-source-fields"
src = "./get-source-fields/index.ts"

[[api.endpoints]]
path = "/get-transformations"
src = "./get-transformations/index.ts"

[[api.endpoints]]
path = "/shopify-oauth"
src = "./shopify-oauth/index.ts"

[[api.endpoints]]
path = "/update-transformation"
src = "./update-transformation/index.ts"

[[api.endpoints]]
path = "/get-dashboard-metrics"
src = "./get-dashboard-metrics/index.ts"

[[api.endpoints]]
path = "/get-analytics-data"
src = "./get-analytics-data/index.ts"

[[api.endpoints]]
path = "/destinations"
src = "./destinations/index.ts"

[[api.endpoints]]
path = "/test-destination-connection"
src = "./test-destination-connection/index.ts"

[[api.endpoints]]
path = "/export-to-destination"
src = "./export-to-destination/index.ts"

[[api.endpoints]]
path = "/destination-webhook"
src = "./destination-webhook/index.ts"

[[api.endpoints]]
path = "/settings"
src = "./settings/index.ts"

[[api.endpoints]]
path = "/help-articles"
src = "./help-articles/index.ts"

[[api.endpoints]]
path = "/onboarding-steps"
src = "./onboarding-steps/index.ts"
