
project_id = "eovyjotxecnkqjylwdnj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[[api.endpoints]]
path = "/destinations/*"
src = "./destinations/index.ts"

[[api.endpoints]]
path = "/help/*"
src = "./help/index.ts"

[[api.endpoints]]
path = "/settings/*"
src = "./settings/index.ts"

[[api.endpoints]]
path = "/sources/*"
src = "./sources/index.ts"

[[api.endpoints]]
path = "/get-analytics-data"
src = "./get-analytics-data/index.ts"

[[api.endpoints]]
path = "/dashboard-data"
src = "./get-dashboard-metrics/index.ts"

[[api.endpoints]]
path = "/shopify-extract"
src = "./shopify-extract/index.ts"

[[api.endpoints]]
path = "/shopify-dependent"
src = "./shopify-dependent/index.ts"
