
project_id = "eovyjotxecnkqjylwdnj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[[api.endpoints]]
path = "/transformations/*"
src = "./transformations/index.ts"

[[api.endpoints]]
path = "/export/*"
src = "./export/index.ts"

[[api.endpoints]]
path = "/sources/*"
src = "./sources/index.ts"

[[api.endpoints]]
path = "/destinations/*"
src = "./destinations/index.ts"

[[api.endpoints]]
path = "/help/*"
src = "./help/index.ts"

[[api.endpoints]]
path = "/settings/*"
src = "./settings/index.ts"

[[api.endpoints]]
path = "/oauth/*"
src = "./oauth/index.ts"

[[api.endpoints]]
path = "/dashboard-data"
src = "./get-dashboard-metrics/index.ts"

[[api.endpoints]]
path = "/analytics"
src = "./get-analytics-data/index.ts"
