
# A string used as a key when handling Deno cache. Using a different cache_key value will force Deno to redownload the dependencies.
cache_key = "v1"

# An array of additional local paths to include as imports in your functions. These are typically used to share code between functions.
imports = []

# An array of scripts to run before the functions are executed.
before_scripts = []

[scripts]
  # A command to run before the function is executed.
  before = []
  # A command to run after the function is executed.
  after = []

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "authorization, x-client-info, apikey, content-type"
